### ISSUE TITLE
Add social media icons at the footer

### ISSUE THREAD

**Issue by GunjanDhanuka** [avinash201199/stopwatch#121]
The web app currently lacks any links to the social media handles or the GitHub repo of the project. I would be happy to add those! Happy Hacktoberfest!

**Comment by ratneshjais** [comment]
Hi, This is a really nice project.
Do you want me to take it to another step by adding the social media links.
Do you have any working social media links?

**Comment by ratneshjais** [comment]
Hi Avinash, I have created the pull request please review it and let me know if anything is missed.

**Comment by ayush-Sharma173** [comment]
Can I work on this issue
