### ISSUE TITLE
Lap record being displayed unnecessarily

### ISSUE THREAD

**Issue by wweverma1** [avinash201199/stopwatch#127]
## Description
While exploring this web app I found some minor issues which I've fixed
- Lap Record section was visible even when it wasn't required
- Clicking upon a button created an rectangular outline around it which didn't matched with button's shape

## Relevant Screenshots
![issue](https://user-images.githubusercontent.com/51537596/140270601-bb909fdd-35a3-485d-94eb-66151502ef1f.png)

**Comment by wweverma1** [comment]
@avinash201199 I've raised a pull request against this issue, PR: https://github.com/avinash201199/stopwatch/pull/128
Kindly review it.

**Comment by avinash201199** [comment]
> @avinash201199 I've raised a pull request against this issue, PR: #128 Kindly review it.

good work
