### ISSUE TITLE
Lap button should only work when timer starts

### ISSUE THREAD

**Issue by Sohamkayal4103** [avinash201199/stopwatch#130]
Please assign this issue to me

**Comment by ayush-Sharma173** [comment]
Please assign this issue to me.
I have completed the code and ready to make PR.
[Screencast from 06-10-22 12:42:50 AM IST.webm](https://user-images.githubusercontent.com/99382234/194143254-8b1344f3-6b12-4333-9e6b-12fe9c265382.webm)
