### ISSUE TITLE
Redesign button

### ISSUE THREAD

**Issue by imobasshir** [avinash201199/stopwatch#15]
Redisign Start stop reset button
Under hacktober

**Comment by shiv0403** [comment]
@imobasshir  can you assign this issue to me

**Comment by avinash201199** [comment]
@imobasshir  don't forget to add screen shot in pr

**Comment by imobasshir** [comment]
ok

**Comment by avinash201199** [comment]
> @imobasshir can you assign this issue to me

@shiv0403  please create your own issue , you can work on footer
