### ISSUE TITLE
Lap and ClearLap function

### ISSUE THREAD

**Issue by Tejaswi-Chaudhari** [avinash201199/stopwatch#17]
![image](https://user-images.githubusercontent.com/62535464/135741660-495d092c-0ea5-4cdd-a70b-6ad3c38b3f24.png)
@avinash201199  Should I raise a PR?

**Comment by avinash201199** [comment]
@Tejaswi-Chaudhari go ahead

**Comment by Tejaswi-Chaudhari** [comment]
@avinash201199 Please review PR #18
