### ISSUE TITLE
responsiveness

### ISSUE THREAD

**Issue by arunsingh009** [avinash201199/stopwatch#44]
It is not reponsive if this is valid issue then please assign this issue to me
![responsive](https://user-images.githubusercontent.com/66819980/135748193-82c717cc-fd64-4dc9-9550-af1712e30b9b.png)

**Comment by avinash201199** [comment]
don't forget to add screen shot  on pr :)
and add issue number to pr

**Comment by arunsingh009** [comment]
for sure thanks for assigning this task to me
