### ISSUE TITLE
Read me can be improved

### ISSUE THREAD

**Issue by ishneet890** [avinash201199/stopwatch#60]

**Comment by ishneet890** [comment]
Please assign this.

**Comment by avinash201199** [comment]
@ishneet890 go ahead :)

**Comment by avinash201199** [comment]
any update ?

**Comment by avinash201199** [comment]
> @avinash201199 pls assign me this Issue. I would like to work on this Issue.

All the best Damini :)

**Comment by komalsoni4** [comment]
please assign me this issue ,I would like to contribute

**Comment by iqrafirdose** [comment]
I would like to contribute in this issue. I will try to update read me more attractive.
