### ISSUE TITLE
Enable dark theme on load if user prefers dark color schemes

### ISSUE THREAD

**Issue by kubikill** [avinash201199/stopwatch#73]
Right now, the page will load using the theme set by user, unless it was never changed then it will load in light theme by default. 
I'd like to change it, so instead of loading light theme by default, the page will use the "prefers-color-scheme" media query to set dark or light mode accordingly until the user manually changes the theme on the page. Please assign me to this issue.

**Comment by avinash201199** [comment]
good work :)
