### ISSUE TITLE
button design can be improved

### ISSUE THREAD

**Issue by Mishthisinghal** [avinash201199/stopwatch#88]
@avinash201199 Can i work on this issue?

**Comment by avinash201199** [comment]
go ahead :)
don't forget to add screen shot of your changes in pr

**Comment by CHIRAGRAGHU** [comment]
Hi , I can improve the button designes by introducing some cool similar color effects in them , try to give me this task.
i asssure you that you will not regret after seeing those designes.

**Comment by komalsoni4** [comment]
Please assign me this issue, I would like to contribute.
