### ISSUE TITLE
Another Functionality: Clear the lap table without resetting the stopwatch

### ISSUE THREAD

**Issue by hitesh181** [avinash201199/stopwatch#93]
The project is good but another functionality can be added to give it provide a more seamless experience. I can help you if you want

**Comment by ompiepy** [comment]
@hitesh181 I think this issue is resolved. If that is the case, this issue should be closed. Is there any issue I can contribute for hactoberfest 2022. Thanks.

**Comment by avinash201199** [comment]
> @hitesh181 I think this issue is resolved. If that is the case, this issue should be closed. Is there any issue I can contribute for hactoberfest 2022. Thanks.

thank you for your contribution
